### PR TITLE
Gh gtk theme 91 fix

### PR DESCRIPTION
**Pull request by isantop**
Fixes pop-os/gtk-theme#91

### CODE REVIEW

**Comment by sysdrum** [comment]
So is this the decided fix?

**Comment by isantop** [comment]
Yes. The Pop Icon theme is designed primarily for use on Pop OS where components from those icon sets won't be installed anyway. And this will prevent the theme from using the breeze theme where it shouldn't be.

**Comment by sysdrum** [comment]
Are there any theme requirements that need any icon sets from anything other then the base theme?

**Comment by isantop** [comment]
Nope! Everything needed is included.

**Comment by jackpot51** [comment]
@isantop Since we fixed this issue in https://github.com/pop-os/default-settings/pull/29, can we close this?

**Pull request closed without merging**
