### PR TITLE
SVG Format Icons

### PR DESCRIPTION
**Pull request by isantop**
Converts the icons from PNG to SVG format

SVG icons are smaller and scalable, so that we don't need to provide icons @2x (or @3x in the future) sizes. They are automatically pixel doubled (and scale sharply) to the required DPI. This allows us to support a theoretically infinite number of DPI scales, particularly integer scaling.

Additionally, if an Icon needs to be scaled up to fit a more arbitrary size, SVG should in theory provide a better experience because they can be scaled to any size. We do lose the crisp design of pixel-perfect integer scaling, but since they're scalable and not raster, it should be clearer than that. 

QA: 
For testing, we need to make sure there are no missing icons and that all of the icons show up correctly in most apps. There aren't any expected issues in switching to SVG, but this should be independently verified.

### CODE REVIEW

**Review by jacobgkau — CHANGES_REQUESTED** [review]
When inspecting this change with gtk4-icon-browser, I found that in the `View Controls` category, the `zoom-in`, `zoom-out`, and `zoom-original` icons used to be themed:

Screenshot from 2022-02-28 14-02-36

After the change, they seem to be falling back to another theme:

Screenshot from 2022-02-28 14-03-17

This does not affect the symbolic version of those icons, just the normal version.

**Comment by isantop** [comment]
> When inspecting this change with gtk4-icon-browser, I found that in the `View Controls` category, the `zoom-in`, `zoom-out`, and `zoom-original` icons used to be themed:
> 
> Screenshot from 2022-02-28 14-02-36
> 
> After the change, they seem to be falling back to another theme:
> 
> Screenshot from 2022-02-28 14-03-17
> 
> This does not affect the symbolic version of those icons, just the normal version.

@jacobgkau  Those are the Pop versions of the full-color icons. They were not rendering correctly prior to this PR.

**Comment by jacobgkau** [comment]
Spotted a regression on a HiDPI system; the regression is not happening on a LoDPI system. In the Archive Manager app, when creating a new archive, the `Location:` dropdown used to show these icons:

archive-old

Now, it shows folder icons instead:

archive-new

I'm almost inclined to believe the former are stock GNOME/Adwaita icons and the latter are Pop icons, but I'm not sure why the "correct" icons would only be showing up on HiDPI if that was the case.

**Comment by isantop** [comment]
@jacobgkau Both are Pop icons; the color versions are the 16x16 versions and the other versions are the larger 32x32+ versions.

It looks like the icon lookup was failing and falling back on the larger icons when it shouldn't have. I've setup a symlink system in the build that will allow the theme to fall back on the correct size icon files. While this means the files are _technically_ half-size, because they're now SVG we can reliably scale them up 2x without them getting blurry, and the icon loader appears to do that successfully. The issue you saw seems to be resolved as of e59cf06

**Review by jacobgkau — CHANGES_REQUESTED** [review]
A number of icons are no longer displaying correctly on 8422437. See the window icon in the launcher, the top-right buttons in GNOME Terminal, and the networking icon in the top-right of GNOME Shell in this screenshot:

Screenshot from 2022-03-10 15-14-34

This also happens on e59cf06, but does not happen back on f5a2a95.

**Comment by isantop** [comment]
70a2ad1 should fix the broken symbolic icons. I would still like to re-render the whole theme, but the icons should at least be usable again

**Comment by isantop** [comment]
Re-rendering the theme resulted in no changes, so 70a2ad1 is ready.

**Comment by 13r0ck** [comment]
Good call to use optimized svgs using the `d` value. :+1:

**Comment by jacobgkau** [comment]
On 70a2ad1, the Archive Manager folder icons are back to using folder icons on HiDPI:

Screenshot from 2022-03-16 09-23-07

LoDPI is still using the color versions:

Screenshot from 2022-03-16 09-24-51

**Comment by isantop** [comment]
@jacobgkau I think I figured out what was causing that. I've updated the packaging to ensure that that won't be an issue anymore. They should now use the full-color icons at both sizes for the small, 16x16 icons

**Comment by jacobgkau** [comment]
Installing this update on a Jammy system, I'm getting a lot of "directory not empty" warnings from dpkg:

<details>
<summary>Output:</summary>

```
Unpacking pop-icon-theme (3.0.0~1649180661~22.04~9fa7783) over (2.1.0~1637164842
~22.04~9998b20) ...
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/8x8@2x/emble
ms': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/sta
tus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/pla
ces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/mim
etypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/emb
lems': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/dev
ices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/cat
egories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/app
s': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/64x64@2x/act
ions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/512x512@2x/p
laces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/sta
tus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/pla
ces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/mim
etypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/emb
lems': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/dev
ices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/cat
egories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/app
s': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/48x48@2x/act
ions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/sta
tus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/pla
ces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/mim
etypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/emb
lems': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/dev
ices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/cat
egories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/app
s': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/32x32@2x/act
ions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/s
tatus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/p
laces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/m
imetypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/d
evices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/c
ategories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/a
pps': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/256x256@2x/a
ctions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/sta
tus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/pla
ces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/mim
etypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/emb
lems': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/dev
ices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/cat
egories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/app
s': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/24x24@2x/act
ions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/sta
tus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/pla
ces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/mim
etypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/emb
lems': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/dev
ices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/cat
egories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/app
s': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/16x16@2x/act
ions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/s
tatus': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/p
laces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/m
imetypes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/d
evices': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/c
ategories': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/a
pps': Directory not empty
dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/128x128@2x/a
ctions': Directory not empty
Setting up pop-icon-theme (3.0.0~1649180661~22.04~9fa7783) ...
```
</details>

Compiling an older version to test, I don't get these warnings when installing 70a2ad1, only the latest commit (9fa7783). Additionally, the package actually failed to install when going from that older commit to the newer commit:

<details>
<summary>Output:</summary>

```
(Reading database ... 200964 files and directories currently installed.)
Preparing to unpack .../pop-icon-theme_3.0.0~1649180661~22.04~9fa7783_all.deb ...
rm: cannot remove '/usr/share/icons/Pop/8x8@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/16x16@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/24x24@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/32x32@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/48x48@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/64x64@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/128x128@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/256x256@2x': No such file or directory
rm: cannot remove '/usr/share/icons/Pop/512x512@2x': No such file or directory
dpkg: error processing archive /var/cache/apt/archives/pop-icon-theme_3.0.0~1649180661~22.04~9fa7783_all.deb (--unpack):
 new pop-icon-theme package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/pop-icon-theme_3.0.0~1649180661~22.04~9fa7783_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
</details>

Are either of these a problem?

**Comment by isantop** [comment]
@jacobgkau I believe the latest commit should have fixed the second issue. I _think_ the first issue is also solved, however it shouldn't be a problem as long as the icons work correctly.

**Comment by jacobgkau** [comment]
7ac113c is still giving me the `dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/.../...': Directory not empty` warnings when installing. As long as this doesn't invalidate my testing and doesn't mean files will look different on a fresh iso built with this update included, the warnings can be ignored.

Everything is looking good on a LoDPI system, but on a HiDPI system, launching gtk4-widget-factory fails with:

```
system76@pop-os:~$ gtk4-widget-factory 

(gtk4-widget-factory:7686): Gdk-ERROR **: 16:09:55.507: Resource path /org/pop-os/themes/Pop/4.0/assets/check@2-symbolic.symbolic.png is not a valid image: The resource at “/org/pop-os/themes/Pop/4.0/assets/check@2-symbolic.symbolic.png” does not exist
Trace/breakpoint trap (core dumped)
```

**Comment by isantop** [comment]
@jacobgkau 

> `(gtk4-widget-factory:7686): Gdk-ERROR **: 16:09:55.507: Resource path /org/pop-os/themes/Pop/4.0/assets/check@2-symbolic.symbolic.png is not a valid image: The resource at “/org/pop-os/themes/Pop/4.0/assets/check@2-symbolic.symbolic.png” does not exist
Trace/breakpoint trap (core dumped)`

This is a GTK Theme Gresource error, not a theme problem

**Review by jacobgkau — APPROVED** [review]
> This is a GTK Theme Gresource error, not a theme problem

Ok, it does happen without this branch too so it's not a regression. gtk3-widget-factory works and everything looks fine in that. (File Roller is also using the correct icons across LoDPI and HiDPI now.)

Tested this on Impish and Jammy, not seeing any further discrepancies beyond what I've already brought up here. Focal has its own master branch and will not be affected.

**Review by 13r0ck — CHANGES_REQUESTED** [review]
I was able to shrink the size of src/scaleable/source-symbolic.svg from ~900kb to ~400kb using inkscape compression. I know that file is not what is loaded at runtime, but I think we should add the same compression to the other SVGs for lower memory usage.

**Comment by 13r0ck** [comment]
Screenshot from 2022-04-12 11-26-08

**Comment by isantop** [comment]
@13r0ck Files are exported from the source document using Inkscape actions, not by exporting manually from within the Inkscape GUI. I may be mistaken here, but I'm not sure there's a way to export SVGs with those options without manually exporting every possible icon file at every size (currently the count is over 2700 files).

**Comment by 13r0ck** [comment]
@isantop inkscape I believe just uses https://github.com/scour-project/scour, can the export script just pass the icons thorough that after exporting from inkscape?

```bash
scour -i input.svg -o output.svg --enable-viewboxing --enable-id-stripping \
  --enable-comment-stripping --shorten-ids --indent=none
```

**Review by n3m0-22 — APPROVED** [review]
I can't find any new issues with the icons. I tested on ```22.04```, ```21.10```, and ```20.04``` on a ```gaze15```and an ```orpy4``` at many different resolutions in both light and dark modes, with diffrent grahics modes, and with diffrent display and icon scaling. I've double checked the previously mentioned issues as well, and they all check out ok. I did notice there are still a bunch of warnings like this when installing ```dpkg: warning: unable to delete old directory '/usr/share/icons/Pop/8x8@2x/emble
ms': Directory not empty```, but based the comment above that's not a problem as long as the icons are working correctly, which the seem to be. This is good to go.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
