### PR TITLE
fix: volume icon when over-amplified

### LINKED ISSUE #101: Volume icon when amplified needs improvement
amplified_speaker_icon
Screenshot from 2021-10-13 14-06-13

### PR DESCRIPTION
**Pull request by 13r0ck**
My attempt to fix #101

### CODE REVIEW

**Comment by jackpot51** [comment]
@isantop correct me if I am wrong, but there is a main file that will also have to be updated, right?

**Comment by 13r0ck** [comment]
Ya something else needs to change. This didn't work

**Comment by isantop** [comment]
That is correct, we need to add the icon to the master file at `src/scalable/source-symbolic.svg`, then the icons are rendered using the included render script

**Review by isantop — COMMENTED** [review]
I've since redesigned the Icon based on feedback from UX about making sure this icon communicates its intended metaphor while also improving its visual appearance. It also provides additional visual distinction from the previous icon.

I believe both @13r0ck and I aren't valid reviews for this PR.

**Review by jacobgkau — APPROVED** [review]
New icon is an improvement (included the current non-overamplified icon for context):
Screenshot from 2021-11-12 15-30-58
Screenshot from 2021-11-12 15-31-04

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
