### PR TITLE
Rename Battery Status Icons like in Gnome/Adwaita

### PR DESCRIPTION
**Pull request by khensunny**
This renaming removes the need for the battery icon fix extension and updates the icon themes to the current naming of icons in Gnome.

### CODE REVIEW

**Review by isantop — APPROVED** [review]
I don't see any reason this shouldn't work. I think removing the extension should happen separately, though.

**Comment by jacobgkau** [comment]
This does eliminate the need for the extension (on Focal and Groovy), although it appears to also break the extension.

**Fully-charged and plugged in:**

Fully-charged current icons w/ extension:

1-fullycharged-withextension-before

Fully-charged current icons w/o extension:

2-fullycharged-noextension-before

Fully-charged renamed icons w/ extension:

3-fullycharged-withextension-after

Fully-charged renamed icons w/o extension:

4-fullycharged-noextension-after

**Under 90%**

Under 90% current icons w/ extension:

5-under90-withextension-before

Under 90% current icons w/o extension:

6-under90-noextension-before

Under 90% renamed icons w/ extension:

7-under90-withextension-after

Under 90% renamed icons w/o extension:

8-under90-noextension-after

**Under 10%:**

Under 10% current icons w/ extension:

17-under10-withextension-before

Under 10% current icons w/o extension:

18-under10-noextension-before

Under 10% renamed icons w/ extension:

19-under10-withextension-after

Under 10% renamed icons w/o extension:

20-under10-noextension-after

**Charging from 0%:**

Charging under 10% current icons w/ extension:

25-charging-withextension-before

Charging under 10% current icons w/o extension:

26-charging-noextension-before

Charging under 10% renamed icons w/ extension:

27-charging-withextension-after

Charging under 10% renamed icons w/o extension:

28-charging-noextension-after

If we're going to move forward with this, the extension needs to be removed at the same time, or the extension needs to be updated to handle the new icon names.

If we don't move forward with this, then the extension would still need some attention:
- With the current icons and extension, it looks like we're currently displaying the 100% icon when we should be showing the fully-charged icon on both Focal and Groovy.
- With the current icons and extension, our custom icons don't show up on the lock screen until the icon is updated/refreshed. Using the renamed icons and no extension, our custom icons show up on the lock screen all the time.

**Comment by mmstick** [comment]
Yeah let's get a PR that removes the package on upgrade, and merge this into a branch in this repo with the same name as that PR so we can test it.

**Comment by mmstick** [comment]
I'll get a PR up soon

**Pull request merged**
