### PR TITLE
docs(dead-links): Fixed dead links in the documentation.

### PR DESCRIPTION
**Pull request by GarnierAdrian**
Some links (on the cursors and src readme) were dead, so I updated the path to fit the current structure:
- src: bitmap -> fullcolor
- cursor: csscursors.html -> test/csscursors.html

### CODE REVIEW

**Review by jacobgkau — APPROVED** [review]
Thank you for the update. Confirmed these links are currently broken, and the new links are valid.

**Comment by GarnierAdrian** [comment]
There is another dead link in the src readme, referencing the Pop.gpl, but I'm not sure if it refers to the Paper.gpl file.

**Comment by jacobgkau** [comment]
> There is another dead link in the src readme, referencing the Pop.gpl, but I'm not sure if it refers to the Paper.gpl file.

Hmm, I see the readme says it's an Inkscape palette but the file itself says it's a GIMP palette. @isantop Do you know if that's the correct file it's trying to link to?

**Comment by isantop** [comment]
It looks like that's the "correct" file; however, we aren't actually using that file in the first place I don't think. I think it should be deleted and the reference removed instead.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
