### PR TITLE
Generate 3x and 96 pixel icons for GNOME Shell

### PR DESCRIPTION
**Pull request by isantop**
GNOME Shell is looking for 96x96 pixel icons for apps (Despite their icons being designed for 64x64px). This means that the icons lookup falls back to scalable icons, which are provided by hicolor but not Pop. 

This PR adds 96px icons for the icon theme by adding 3x-generated icons and using 48@2x for 96x96 and 64@3x for 96@2x. This should eventually be replaced with actual 96px icons in the theme, but this will suffice for now.

### CODE REVIEW

**Comment by isantop** [comment]
@brs17 Testing notes:

Some icons will be a bit derpy-looking in the application overview with this PR. This is due to using double-resoluti0on 48px files instead of native 96px icons. They will be sharp, but elements (like borders) will be double the number of pixels compared to what they "should" have. This will be addressed in a future PR that adds native 96px icons, but since that requires drawing a 96px version of every icon, we are doing this to ensure coverage and pixel-alignment.

**Comment by jackpot51** [comment]
I will take a look at this tomorrow

**Comment by jackpot51** [comment]
This will not work. gnome-shell is demanding scalable icons. It made requests for icons of size _94_

I am looking into addressing this in gnome-shell

**Comment by jackpot51** [comment]
The icons in folders are size *_37_*

**Pull request closed without merging**
