### PR TITLE
Selection checked

### PR DESCRIPTION
**Pull request by isantop**
Adds a selection-checked-symbolic icon. Required for pop-os/installer#199

### CODE REVIEW

**Comment by isantop** [comment]
@pop-os/quality-assurance For QA testing this, please ensure that nothing breaks on upgrade, and that after upgrading the path `/usr/share/icons/Pop/scalable/actions/selection-checked-symbolic.svg` exists.

Thanks

**Comment by brs17** [comment]
~My hesitation here is how this would look on 18.04 where the highlight color is blue, that may contrast a lot with this grey checkmark (where as currently the checkmark in 18.04 is white).~

EDIT: The hightlight color is blue in both 19.10 and 18.04, I am not sure what that would look like (contrast wise).

@mmstick Do you think you could get a pr ready as detailed here: https://github.com/pop-os/installer/issues/199#issuecomment-540067570 ? That would probably be the best way to test this out and come to a final conclusion.

**Comment by isantop** [comment]
@brs17 Symbolic icons are colored dynamically by GTK. This will contrast no matter what theme is present because the theme can set the color dynamically.

**Comment by leviport** [comment]
I might need a hand going over this one tomorrow morning. From a live disk, I applied the patch, installed updates, restarted Gnome, and restarted the installer, but I'm still seeing the same icon as before. I'm probably missing something, but I'm not quite sure what it is.

selection-checked-seems-same

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@leviport it appears that the pop-installer was not built, I am working on that now but need this to be in proposed to do correct ISO testing

**Pull request merged**
