### PR TITLE
Remove files with spaces

### LINKED ISSUE #30: Installation failed [Makefile Error]
**Reporter info**

 * Distribution - Fedora 27 
 * Gtk+ 3.0 version - 3.22.26-2
 * Desktop environment - GNOME 3.26

**Steps to reproduce (if you knew)**
sudo make install
sudo make post-install
screenshot from 2018-04-23 19-45-19

### PR DESCRIPTION
**Pull request by isantop**
Removes a file which had a space in its filename. This caused installation errors for some users installing from git on some OSs.

Fixes #30

### CODE REVIEW

**Comment by brs17** [comment]
In trying to confirm that it fixes #30, I tried to install the icon theme from source in Ubuntu 18.10 and got the following error after running `sudo  make post-install`:
```
gtk-update-icon-cache: Mo theme index file.
make: [Makefile:22: post-install] Error 1 (ignored)
```

**Comment by jackpot51** [comment]
@isantop @brs17 please resolve the issues with this

**Comment by isantop** [comment]
```
gtk-update-icon-cache -q /usr/share/icons/Pop-Extra
gtk-update-icon-cache: No theme index file.
make: [Makefile:22: post-install] Error 1 (ignored)
```

This appears to have been caused by the Pop-Extra theme split, and was not introduced in this PR. It also occurs with master.

**Comment by isantop** [comment]
@brs17 This has been ready for re-review since January.

**Comment by brs17** [comment]
My initial understanding of https://github.com/pop-os/icon-theme/issues/30 was of the error returned when building the theme. It appears that the issue in https://github.com/pop-os/icon-theme/issues/30 kind of changes from the person who made the issue to later comments.  This patch seems to fix the later issue though. :+1: 

I do think though that that issue is for those build errors, and the space in the file names should have been moved to a separate issue. 

Maybe we don't close that issue?

**Comment by isantop** [comment]
30 is a technically different error. The one in question was introduced exclusively by #33.

**Pull request merged**
