### PR TITLE
fix: Update cursor theme to current Yaru version

### LINKED ISSUE #155: Accessibility cursor size setting: two largest cursor sizes don't work
In Accessibility, the Cursor Size selector only changes the cursor size between the three smallest options. The two larger sizes on the right seem to only switch to the middle size, though it was reported [in a recent review video](https://youtu.be/Mie3vxD4O6g?t=800) that the cursor size doesn't change at all.

cursorsize

I tested on oryp6 running 20.10 in Integrated, Compute, and Nvidia modes and saw the same behavior across all three modes.

### PR DESCRIPTION
**Pull request by ids1024**
Assumes we have/want no changes relative to Yaru for the cursor theme. I believe that's correct.

Yaru commit 4f1d31c5d4de784e9671cadf1303a9ba14f9f0cd, for what it's worth.

Fixes https://github.com/pop-os/gnome-control-center/issues/155

### CODE REVIEW

**Comment by leviport** [comment]
I'm not sure why, but my pointer seems even more broken after this patch. The size doesn't adjust at all, and the theme seems like it varies from the pointers shown in the size preview. Gnome-tweaks still shows that I have the Pop cursor theme active, but it definitely feels like it fell back on some kind of default cursor theme.

cursorsize2

**Comment by ids1024** [comment]
Strange. For me it works exactly as expected, with the Pop cursor theme selected in Gnome Tweaks. For each size the cursor seems to match the style and size of the selected option.

**Comment by leviport** [comment]
Yeah I'm not sure. I even nuked and paved the oryp6 to try again and it's giving me the same thing. All I did from the clean install was add the branch and upgrade.

**Comment by ids1024** [comment]
Update: it was installing to `/usr/share/icons/Pop/cursors/cursors` instead of `/usr/share/icons/Pop/cursors`, so I'm not sure why it was **working** for me earlier. :laughing: 

Hopefully it doesn't have issues anymore.

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
Working on 20.10 as of last update. 

Cursor_scale

**Review by leviport — APPROVED** [review]
It's looking great now.

**Pull request merged**
