### PR TITLE
Update Cursors

### PR DESCRIPTION
**Pull request by isantop**
The current cursor theme is unmaintainable. There was previously a bug related to rendering cursors for HiDPI output which was fixed by copy-pasting the Yaru cursors into the current theme. While this fixed the cursors for HiDPI, the ones we got had some visual issues making them slightly weird (several of the cursors were black-on-white instead of white-on-black like the main ones) and the existing rendering could not integrate with the tooling. 

This PR fixes both of these issues by developing all-new rendering tooling for the cursors and integrating it into the master-rendering system. This change means that every file in the output directory will now be generated by the `master-render.py` command, greatly improving our resiliency to issues in the future. It also updates the visuals of the cursors to be a unified light-foreground/dark-background color scheme, eliminating random color shifts when using various cursors.

With this change, the cursors' visual appearance is updated to be uniform for all cursors, the rendering system for cursors is implemented and integrated, and the rendering script is improved to ensure that every file in the theme is correctly generated each time it is run.

### CODE REVIEW

**Comment by gangwerz** [comment]
The new cursors worked great on Pop 22.04. Since the Focal build failed, I was unable to install on 20.04 with the staging repo. I built from source and tested. No regressions were found on 20.04 either.

**Comment by isantop** [comment]
> The new cursors worked great on Pop 22.04. Since the Focal build failed, I was unable to install on 20.04 with the staging repo. I built from source and tested. No regressions were found on 20.04 either.

This won't affect focal anyway, since there's a separate `mater_focal` branch

**Comment by gangwerz** [comment]
In that case, the changes look good! I approve the changes, but the approval page keeps crashing. I will ask an admin to push through the approval when they can.

**Review by leviport — APPROVED** [review]

**Comment by leviport** [comment]
Seems that opening https://github.com/pop-os/icon-theme/pull/122/files in chromium worked fine. Somehow it also made it start loading in Firefox as well.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
