### PR TITLE
New window symbolic icon

### PR DESCRIPTION
**Pull request by isantop**
Adds an icon for `new-window-symbolic`, which is being used by the launcher in Pop-shell

### CODE REVIEW

**Review by jackpot51 — COMMENTED** [review]
Looks like this also adds a dozen symbolic battery icons, is that expected?

**Comment by jackpot51** [comment]
@isantop please also make sure shell is using this new icon: https://github.com/pop-os/shell/issues/1026

**Comment by jacobgkau** [comment]
It looks like the battery icons being added here were previously renamed in https://github.com/pop-os/icon-theme/pull/78.

**Comment by isantop** [comment]
#78 does not appear to have been set up correctly. Those icons can be removed, but #78 should be redone to make the changes to the master file (to avoid this happening again in the future)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
